#By default, all web endpoints are available beneath the path
#/actuator with URLs of the form /actuator/{id}.
#The /actuator base path can be configured by using the
#management.endpoints.web.base-path property,
#as shown in the following example:
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'
  
# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger
  # /api-docs endpoint custom path
  api-docs:
    path: /docs
  #In order to display spring-boot-actuator endpoints, simply add the following property:
  show-actuator: true
    
# #logging    
# logging:
#   level:
#     web: DEBUG



