# server port configuration
server:
  port: 8104

#spring app configuration
spring:

  #mongodb configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: newsappproject


#wishlist app properties
wishlist:
  welcome:
    message: Hello, This is Wishlist Server
  #endpoints
  endpoint:
    common: /newsapp/v1/wishlist
    welcome: /welcome
    add-to-wishlist: /add
    remove-from-wishlist: /remove
    get-wishlist: /get
