# server port configuration
server:
  port: 8102

#spring app configuration
spring:
  #mysql database configuration
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

#user-profile app properties
user-profile:
  welcome:
    message: Hello, This is User Profile Server